"""initial

Revision ID: 54825a348b4f
Revises: 
Create Date: 2020-07-17 18:40:39.088745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54825a348b4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_table_b')),
    sa.UniqueConstraint('name', name=op.f('uq_table_b_name'))
    )
    op.create_table('table_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('table_b', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_b'], ['table_b.id'], name=op.f('fk_9d68bd30-b17a-565a-aee7-7bd21e90672e')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_table_a')),
    sa.UniqueConstraint('name', name=op.f('uq_table_a_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_a')
    op.drop_table('table_b')
    # ### end Alembic commands ###
